### PR TITLE
Parsefiles

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by TristanWright** [comment]
fixes #14, will take another look on Monday to make sure I'm definitely not breaking anything.

**Comment by TristanWright** [comment]
So, I can import a full ini file and export it, the only difference is the backend section which the parser is not covering.

screen shot 2016-10-03 at 11 55 37

**Comment by patrickoleary** [comment]
Awesome!

**Comment by cjh1** [comment]
@TristanWright Great! For our use case we aren't interest in the backend section, however, I wonder if is possible to support this for others?

**Pull request merged**
